### ISSUE TITLE
Replace boilerplate code with FOCA archetype

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-europe/proWES#10]
A lot of the code shared between this service and others in the organizationhas been moved to the [FOCA](https://github.com/elixir-cloud-aai/foca) archetype.

Duplicate code should be removed from this service and, where necessary, the remaining code should be refactored to make use of FOCA.

**Comment by anuragxxd** [comment]
Working on this. @sarthakgupta072 @uniqueg

**Comment by anuragxxd** [comment]
For this I think we need to change the foca repo also to add some more functionality about mongo and more security. @sarthakgupta072 @uniqueg.
Right Now mongo util file contains only the few operation in foca but we are using more of queries here.

**Comment by uniqueg** [comment]
Answered in Slack
